apiVersion: v2
name: homarr
description: A Helm chart to deploy homarr for Kubernetes
home: https://homarr-labs.github.io/charts/charts/homarr/
type: application
version: 1.1.0
# renovate datasource=docker depName=ghcr.io/homarr-labs/homarr
appVersion: "v1.0.0-beta.10"
icon: https://raw.githubusercontent.com/homarr-labs/charts/refs/heads/main/charts/homarr/icon.svg
kubeVersion: ">=1.22.0-0"
dependencies:
  - name: mysql
    repository: "https://charts.bitnami.com/bitnami"
    condition: mysql.internal
    version: "12.2.0"
keywords:
  - homarr
  - dashboard
sources:
  - https://github.com/homarr-labs/homarr
annotations:
  artifacthub.io/signKey: |
    fingerprint: 36F9A886ABA6AA4C1588B942E7EC1AA0EFD54840
    url: https://homarr-labs.github.io/charts/pgp_keys.asc
  artifacthub.io/changes: |-
    - kind: changed
      description: update SSO env variables
  artifacthub.io/links: |-
    - name: App Source
      url: https://github.com/homarr-labs/homarr
    - name: Chart Source
      url: https://github.com/homarr-labs/charts/tree/main/charts/homarr
