name: Update Chart Metadata

on:
  push:
    branches:
      - renovate/**

env:
  COMMIT_MESSAGE: "chore: Update chart metadata"

jobs:
  update-chart-metadata:
    name: Update Chart Metadata
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Detect Changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          list-files: shell
          filters: |
            charts:
              - charts/**

      - name: Fetch PR
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.repos.listPullRequestsAssociatedWithCommit({
              owner: context.repo.owner,
              repo: context.repo.repo,
              commit_sha: context.sha,
            });
            const pr = response.data.shift();
            core.setOutput("title", pr.title);
            core.setOutput("base_ref", pr.base.ref);
            core.setOutput("labels", pr.labels.map((e) => e.name).filter((e) => e));

      - name: Check PR Title
        id: pr_title_check
        run: |
          set -eu
          if [[ "${{ steps.pr.outputs.title }}" == *"ghcr.io/homarr-labs/homarr docker tag"* || \
                "${{ steps.pr.outputs.title }}" == *"update mysql helm release"* ]]; then
            echo "result=true" >> $GITHUB_OUTPUT
          else
            echo "result=false" >> $GITHUB_OUTPUT
          fi

      - name: Update changelog
        if: steps.pr_title_check.outputs.result == 'true'
        env:
          TITLE: ${{ steps.pr.outputs.title }}
          CHANGELOG_APPEND: ${{ contains(steps.pr.outputs.labels, 'changelog-append') }}
        run: |
          set -eux
          export DESCRIPTION="$(perl -pe 's/^.+?: (.)/\U$1/' <<<"$TITLE")"
          ./hack/update-changelog.sh "changed" "$DESCRIPTION"

      - name: Set type to patch
        if: steps.pr_title_check.outputs.result == 'true' &&
          (contains(steps.pr.outputs.labels, 'patch') || contains(steps.pr.outputs.labels, 'digest'))
        run: echo TYPE=patch >>$GITHUB_ENV
      - name: Set type to minor
        if: steps.pr_title_check.outputs.result == 'true' &&
          (contains(steps.pr.outputs.labels, 'major') || contains(steps.pr.outputs.labels, 'minor'))
        run: echo TYPE=minor >>$GITHUB_ENV
      - name: Update chart version
        if: steps.pr_title_check.outputs.result == 'true' &&
          !contains(steps.pr.outputs.labels, 'skip-version-bump')
        run: |
          set -eux
          ./hack/update-version.sh "$TYPE"

      - name: Install helm-docs
        if: steps.pr_title_check.outputs.result == 'true'
        uses: gabe565/setup-helm-docs-action@v1
      - name: Generate Helm docs
        if: steps.pr_title_check.outputs.result == 'true'
        run: |
          set -eu
          ./hack/gen-helm-docs.sh

      - name: Check if commit exists
        if: steps.pr_title_check.outputs.result == 'true'
        id: commit_exists
        env:
          BASE_REF: ${{ steps.pr.outputs.base_ref }}
        run: |
          set -eu
          IFS=$'\n\t'
          commits="$(git rev-list --pretty=oneline "origin/$BASE_REF..HEAD" | cut -d' ' -f2-)"
          if grep -F -e "$COMMIT_MESSAGE" <<<"$commits"; then
            echo 'result=true' >>$GITHUB_OUTPUT
          else
            echo 'result=false' >>$GITHUB_OUTPUT
          fi

      - name: Commit chart version
        if: steps.pr_title_check.outputs.result == 'true' &&
          steps.commit_exists.outputs.result == 'false' &&
          !contains(steps.pr.outputs.labels, 'skip-chart-meta')
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: ${{ env.COMMIT_MESSAGE }}
